import { v4 as uuidv4 } from 'uuid';

const data = {
    empresa: {
        nombre: "JuanquiDev Tech",
        direccion: {
            nombre_calle: "Calle Tech",
            numero_calle: 5,
            piso_calle: 4,
            letra_calle: "d",
            codigo_postal: 14007,
            provincia: "Córdoba",
            ccaa: "Andalucía",
            pais: "España",
        },
        cif: "B170089D",
        telefono: "+34 200 000 673",
        correo_empresa: "empresa@cordoba.fakeapi.com"
    },
    departamentos: [
        {
            id_departamento: uuidv4(),
            nombre_departamento: "Desarrollo",
            jefe_departamento: "Blanca Oferall",
            presupuesto_anual_departamento: 300000,
            empleados_departamento: [
                {
                    "id_empleado": "b436ec29-5d1c-4380-97e4-546d0ea087b8",
                    "nombre_empleado": "Véronique",
                    "apellidos_empleado": "Muzzall",
                    "email_empleado": "kmuzzall0@gmpg.org",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Community Outreach Specialist",
                    "salario_anual_empleado": 82668,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/sitdelectusnesciunt.png?size=50x50&set=set1",
                    "codigo_acceso": "36987-1183"
                },
                {
                    "id_empleado": "35e7e1b3-48fe-4f4e-a027-a94eae0e73ff",
                    "nombre_empleado": "Marie-noël",
                    "apellidos_empleado": "Levermore",
                    "email_empleado": "llevermore1@studiopress.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Executive Secretary",
                    "salario_anual_empleado": 63864,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/etveniamut.png?size=50x50&set=set1",
                    "codigo_acceso": "0527-1343"
                },
                {
                    "id_empleado": "511612ad-ebf5-4769-b0eb-4abae721bc60",
                    "nombre_empleado": "Gérald",
                    "apellidos_empleado": "Nasi",
                    "email_empleado": "rnasi2@wired.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Accounting",
                    "salario_anual_empleado": 42577,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/eiusexpeditadoloremque.png?size=50x50&set=set1",
                    "codigo_acceso": "0363-0547"
                },
                {
                    "id_empleado": "417df524-66d8-4300-b7ea-f300145cdc28",
                    "nombre_empleado": "Mélodie",
                    "apellidos_empleado": "Dafter",
                    "email_empleado": "ldafter3@dion.ne.jp",
                    "genero_empleado": "Female",
                    "puesto_empleado": "GIS Technical Architect",
                    "salario_anual_empleado": 53620,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quosetneque.png?size=50x50&set=set1",
                    "codigo_acceso": "63629-1621"
                },
                {
                    "id_empleado": "8858f720-b6c7-4348-b301-2b9c47449188",
                    "nombre_empleado": "Hélèna",
                    "apellidos_empleado": "Summerskill",
                    "email_empleado": "lsummerskill4@geocities.jp",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Sales",
                    "salario_anual_empleado": 79183,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/innobisvelit.png?size=50x50&set=set1",
                    "codigo_acceso": "49288-0330"
                },
                {
                    "id_empleado": "062df6f9-a20a-40a9-b8ae-782711a43c9e",
                    "nombre_empleado": "Marie-noël",
                    "apellidos_empleado": "Ugoletti",
                    "email_empleado": "eugoletti5@timesonline.co.uk",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Nuclear Power Engineer",
                    "salario_anual_empleado": 63403,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/sintetbeatae.png?size=50x50&set=set1",
                    "codigo_acceso": "33261-904"
                },
                {
                    "id_empleado": "3eb584b5-46ae-4f93-b23a-8b1df04323fc",
                    "nombre_empleado": "Fèi",
                    "apellidos_empleado": "Browett",
                    "email_empleado": "cbrowett6@nytimes.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Account Representative II",
                    "salario_anual_empleado": 84639,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/autemutet.png?size=50x50&set=set1",
                    "codigo_acceso": "43846-0003"
                },
                {
                    "id_empleado": "4a8ff94d-06b1-4f6e-b29b-ea5be05b393b",
                    "nombre_empleado": "Esbjörn",
                    "apellidos_empleado": "Leeder",
                    "email_empleado": "sleeder7@globo.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Software Test Engineer I",
                    "salario_anual_empleado": 57387,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/voluptasnecessitatibusmodi.png?size=50x50&set=set1",
                    "codigo_acceso": "75939-9876"
                },
                {
                    "id_empleado": "942aa25d-7967-4ec5-a31a-7e77aedf390c",
                    "nombre_empleado": "Médiamass",
                    "apellidos_empleado": "Hoyer",
                    "email_empleado": "bhoyer8@sciencedaily.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Account Representative I",
                    "salario_anual_empleado": 61606,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/distinctioadquasi.png?size=50x50&set=set1",
                    "codigo_acceso": "67345-6080"
                },
                {
                    "id_empleado": "8e50ff73-471f-4f43-9aa9-c29b2ffd23b4",
                    "nombre_empleado": "Gwenaëlle",
                    "apellidos_empleado": "Carless",
                    "email_empleado": "lcarless9@state.tx.us",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Financial Advisor",
                    "salario_anual_empleado": 62673,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/voluptatumdoloremnumquam.png?size=50x50&set=set1",
                    "codigo_acceso": "0378-0334"
                },
                {
                    "id_empleado": "5f2f4aab-b0ec-496d-b73f-470a4cec17b4",
                    "nombre_empleado": "Lucrèce",
                    "apellidos_empleado": "Galvin",
                    "email_empleado": "fgalvina@guardian.co.uk",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Computer Systems Analyst IV",
                    "salario_anual_empleado": 69046,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/essequosmagni.png?size=50x50&set=set1",
                    "codigo_acceso": "10096-0214"
                },
                {
                    "id_empleado": "c2b476c7-e052-4c6f-a775-65382186298e",
                    "nombre_empleado": "Andréa",
                    "apellidos_empleado": "Kemme",
                    "email_empleado": "tkemmeb@cafepress.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Business Systems Development Analyst",
                    "salario_anual_empleado": 40620,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/molestiaemagniamet.png?size=50x50&set=set1",
                    "codigo_acceso": "76354-112"
                },
                {
                    "id_empleado": "4fbc897f-be78-4803-8654-7d5ee5bb3cab",
                    "nombre_empleado": "Marie-françoise",
                    "apellidos_empleado": "Wilder",
                    "email_empleado": "kwilderc@imgur.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Senior Cost Accountant",
                    "salario_anual_empleado": 45716,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/molestiaenihilpariatur.png?size=50x50&set=set1",
                    "codigo_acceso": "0781-2261"
                },
                {
                    "id_empleado": "78174f48-6a62-4269-81af-92c53dcf8df0",
                    "nombre_empleado": "Néhémie",
                    "apellidos_empleado": "Nuschke",
                    "email_empleado": "bnuschked@google.com.hk",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Office Assistant IV",
                    "salario_anual_empleado": 40914,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/estfugitaut.png?size=50x50&set=set1",
                    "codigo_acceso": "54799-507"
                },
                {
                    "id_empleado": "ab4f56a5-3f57-4c44-9ef5-6a39332905cb",
                    "nombre_empleado": "Bénédicte",
                    "apellidos_empleado": "Learoyde",
                    "email_empleado": "alearoydee@time.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Tax Accountant",
                    "salario_anual_empleado": 36384,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/odiovelsint.png?size=50x50&set=set1",
                    "codigo_acceso": "58232-0225"
                },
                {
                    "id_empleado": "593b3e9a-672c-4b0a-aa64-ae9f50374d1f",
                    "nombre_empleado": "Miléna",
                    "apellidos_empleado": "See",
                    "email_empleado": "cseef@webeden.co.uk",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Help Desk Operator",
                    "salario_anual_empleado": 57981,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/reprehenderitnihilaliquam.png?size=50x50&set=set1",
                    "codigo_acceso": "12634-691"
                },
                {
                    "id_empleado": "5141a3b2-8593-4ab8-9694-b5c01ebfbd0f",
                    "nombre_empleado": "Mårten",
                    "apellidos_empleado": "Stowell",
                    "email_empleado": "vstowellg@yellowbook.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Editor",
                    "salario_anual_empleado": 87184,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/repudiandaealiasullam.png?size=50x50&set=set1",
                    "codigo_acceso": "14783-437"
                },
                {
                    "id_empleado": "c9c1c09f-61da-427d-a0ed-707eaf2b64ca",
                    "nombre_empleado": "Yénora",
                    "apellidos_empleado": "Kenaway",
                    "email_empleado": "lkenawayh@oaic.gov.au",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Administrative Assistant II",
                    "salario_anual_empleado": 83993,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quasidoloremsapiente.png?size=50x50&set=set1",
                    "codigo_acceso": "50481-3201"
                },
                {
                    "id_empleado": "a25dbfce-345a-4f4c-9b17-487b8c682944",
                    "nombre_empleado": "Mégane",
                    "apellidos_empleado": "Rappaport",
                    "email_empleado": "brappaporti@behance.net",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Staff Scientist",
                    "salario_anual_empleado": 76342,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/consequaturevenietest.png?size=50x50&set=set1",
                    "codigo_acceso": "11673-000"
                },
                {
                    "id_empleado": "c0afcb7c-6aa5-4e51-bd2c-e781635fd99e",
                    "nombre_empleado": "Estée",
                    "apellidos_empleado": "Leads",
                    "email_empleado": "cleadsj@amazon.de",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Graphic Designer",
                    "salario_anual_empleado": 42520,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/nostrumquisquamut.png?size=50x50&set=set1",
                    "codigo_acceso": "0603-4080"
                },
                {
                    "id_empleado": "37974a1c-9fcb-4c5d-9a01-5e97987738c9",
                    "nombre_empleado": "Bérénice",
                    "apellidos_empleado": "Slane",
                    "email_empleado": "eslanek@bbc.co.uk",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Programmer IV",
                    "salario_anual_empleado": 45077,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/delectusipsaa.png?size=50x50&set=set1",
                    "codigo_acceso": "61481-0037"
                },
                {
                    "id_empleado": "8c8b2d81-78c8-45ee-b049-44188aef1b9a",
                    "nombre_empleado": "Noémie",
                    "apellidos_empleado": "Kristiansen",
                    "email_empleado": "akristiansenl@creativecommons.org",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Accountant IV",
                    "salario_anual_empleado": 67927,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/nullaeteos.png?size=50x50&set=set1",
                    "codigo_acceso": "64117-241"
                },
                {
                    "id_empleado": "0866b0cd-ff33-472e-964c-acb674fbf775",
                    "nombre_empleado": "Åke",
                    "apellidos_empleado": "Barrass",
                    "email_empleado": "ebarrassm@aol.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Junior Executive",
                    "salario_anual_empleado": 85335,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/corporisquaeratunde.png?size=50x50&set=set1",
                    "codigo_acceso": "55154-6328"
                },
                {
                    "id_empleado": "c228a5ea-18d3-4a1d-bf8a-f5c6b066fe9e",
                    "nombre_empleado": "Léonore",
                    "apellidos_empleado": "Wavell",
                    "email_empleado": "cwavelln@harvard.edu",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Executive Secretary",
                    "salario_anual_empleado": 79832,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/quosquisut.png?size=50x50&set=set1",
                    "codigo_acceso": "67938-0859"
                },
                {
                    "id_empleado": "90fd92e4-f819-427a-a819-a676e1fc34e4",
                    "nombre_empleado": "Maïté",
                    "apellidos_empleado": "Samsonsen",
                    "email_empleado": "asamsonseno@bandcamp.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Product Management",
                    "salario_anual_empleado": 47632,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/facilisomnisdolorem.png?size=50x50&set=set1",
                    "codigo_acceso": "0955-1012"
                },
                {
                    "id_empleado": "63d62005-e2a6-4c7b-aaac-b4b33761f66c",
                    "nombre_empleado": "Maëlann",
                    "apellidos_empleado": "Ralph",
                    "email_empleado": "kralphp@mtv.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Graphic Designer",
                    "salario_anual_empleado": 88744,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/nequemaioresvoluptatem.png?size=50x50&set=set1",
                    "codigo_acceso": "68788-0802"
                },
                {
                    "id_empleado": "315014d1-5cc5-467b-a5e0-8f626e457050",
                    "nombre_empleado": "Méline",
                    "apellidos_empleado": "Schapero",
                    "email_empleado": "cschaperoq@weebly.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Food Chemist",
                    "salario_anual_empleado": 38440,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/repudiandaequaeeius.png?size=50x50&set=set1",
                    "codigo_acceso": "49349-269"
                },
                {
                    "id_empleado": "d99aeb2b-4f90-45d5-88e1-e6d871770672",
                    "nombre_empleado": "Naéva",
                    "apellidos_empleado": "Gluyus",
                    "email_empleado": "kgluyusr@pagesperso-orange.fr",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Operator",
                    "salario_anual_empleado": 35213,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/voluptateaet.png?size=50x50&set=set1",
                    "codigo_acceso": "68987-013"
                },
                {
                    "id_empleado": "94109790-c0bc-418e-9d40-ca41447522b7",
                    "nombre_empleado": "Naëlle",
                    "apellidos_empleado": "Fermer",
                    "email_empleado": "jfermers@weather.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Pharmacist",
                    "salario_anual_empleado": 48967,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/ullametalias.png?size=50x50&set=set1",
                    "codigo_acceso": "59667-0010"
                },
                {
                    "id_empleado": "5eb37b93-e5c9-4213-8507-632197ab2fe6",
                    "nombre_empleado": "Loïca",
                    "apellidos_empleado": "McDaid",
                    "email_empleado": "smcdaidt@cmu.edu",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Research Nurse",
                    "salario_anual_empleado": 26239,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/sedinciduntoccaecati.png?size=50x50&set=set1",
                    "codigo_acceso": "52533-005"
                },
                {
                    "id_empleado": "d7932e2d-89ea-4fd2-83ad-56048989e72f",
                    "nombre_empleado": "Anaël",
                    "apellidos_empleado": "Fernier",
                    "email_empleado": "wfernieru@soundcloud.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Technical Writer",
                    "salario_anual_empleado": 76047,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/vitaeinciduntet.png?size=50x50&set=set1",
                    "codigo_acceso": "51079-206"
                },
                {
                    "id_empleado": "3043e3f5-c296-4474-b2ea-20645ad321d9",
                    "nombre_empleado": "Alizée",
                    "apellidos_empleado": "Fitzsymon",
                    "email_empleado": "afitzsymonv@chronoengine.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Software Consultant",
                    "salario_anual_empleado": 72755,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/magnamfugiatvoluptas.png?size=50x50&set=set1",
                    "codigo_acceso": "49035-331"
                },
                {
                    "id_empleado": "63ecac20-1094-45cb-aed6-8db804d52f05",
                    "nombre_empleado": "Magdalène",
                    "apellidos_empleado": "Iacobini",
                    "email_empleado": "hiacobiniw@behance.net",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Web Designer I",
                    "salario_anual_empleado": 46687,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/saepequiaqui.png?size=50x50&set=set1",
                    "codigo_acceso": "35356-298"
                },
                {
                    "id_empleado": "ece1c2e9-80ae-4faa-947f-90b76e598714",
                    "nombre_empleado": "Cécile",
                    "apellidos_empleado": "Blumsom",
                    "email_empleado": "cblumsomx@unicef.org",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Account Executive",
                    "salario_anual_empleado": 80549,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/laborumteneturrerum.png?size=50x50&set=set1",
                    "codigo_acceso": "63304-161"
                },
                {
                    "id_empleado": "7cd89a9e-a518-4222-a388-a1b910f87160",
                    "nombre_empleado": "Mélys",
                    "apellidos_empleado": "Alwell",
                    "email_empleado": "falwelly@barnesandnoble.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Human Resources Assistant IV",
                    "salario_anual_empleado": 26923,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/estquoslaborum.png?size=50x50&set=set1",
                    "codigo_acceso": "55289-660"
                },
                {
                    "id_empleado": "02fea215-dfb1-4910-82f1-2702044356d5",
                    "nombre_empleado": "Daphnée",
                    "apellidos_empleado": "Skellon",
                    "email_empleado": "lskellonz@bandcamp.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Nurse Practicioner",
                    "salario_anual_empleado": 30403,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/dictarecusandaequidem.png?size=50x50&set=set1",
                    "codigo_acceso": "21839-101"
                },
                {
                    "id_empleado": "25a610c9-c416-4073-a37c-2bcdafbe986f",
                    "nombre_empleado": "Torbjörn",
                    "apellidos_empleado": "Pauling",
                    "email_empleado": "npauling10@mac.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Librarian",
                    "salario_anual_empleado": 89583,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/cumquetotama.png?size=50x50&set=set1",
                    "codigo_acceso": "49288-0926"
                },
                {
                    "id_empleado": "a2974470-1056-49ed-8f2f-77b86a9d4a73",
                    "nombre_empleado": "Bérengère",
                    "apellidos_empleado": "Gresley",
                    "email_empleado": "rgresley11@shutterfly.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Graphic Designer",
                    "salario_anual_empleado": 74390,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/consequaturlaboreab.png?size=50x50&set=set1",
                    "codigo_acceso": "63824-193"
                },
                {
                    "id_empleado": "2472fd5d-4f84-4718-a4b9-ade4967b4122",
                    "nombre_empleado": "Garçon",
                    "apellidos_empleado": "Elwill",
                    "email_empleado": "jelwill12@devhub.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Help Desk Operator",
                    "salario_anual_empleado": 87838,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/utcorruptivitae.png?size=50x50&set=set1",
                    "codigo_acceso": "0187-0498"
                },
                {
                    "id_empleado": "771e3c57-74bc-4ecf-80bb-2787484d7d05",
                    "nombre_empleado": "Cécilia",
                    "apellidos_empleado": "Tooze",
                    "email_empleado": "ftooze13@google.co.jp",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Research Nurse",
                    "salario_anual_empleado": 65210,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/magnamquasmolestias.png?size=50x50&set=set1",
                    "codigo_acceso": "55758-001"
                },
                {
                    "id_empleado": "5dd08d3f-4e24-4740-8582-0d8553c51af6",
                    "nombre_empleado": "Mélia",
                    "apellidos_empleado": "Gile",
                    "email_empleado": "kgile14@unc.edu",
                    "genero_empleado": "Genderqueer",
                    "puesto_empleado": "Geologist III",
                    "salario_anual_empleado": 50560,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quiaiddoloribus.png?size=50x50&set=set1",
                    "codigo_acceso": "98132-890"
                },
                {
                    "id_empleado": "4e1d4a03-9eee-4080-ba65-b5745f81b587",
                    "nombre_empleado": "Sòng",
                    "apellidos_empleado": "Howen",
                    "email_empleado": "fhowen15@1688.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Staff Scientist",
                    "salario_anual_empleado": 78029,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/delectusetquod.png?size=50x50&set=set1",
                    "codigo_acceso": "59779-442"
                },
                {
                    "id_empleado": "c0fbb848-b14a-42cb-9c9f-a493bca1dfc3",
                    "nombre_empleado": "Vénus",
                    "apellidos_empleado": "Fulger",
                    "email_empleado": "afulger16@acquirethisname.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Clinical Specialist",
                    "salario_anual_empleado": 56516,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/laboriosamutdignissimos.png?size=50x50&set=set1",
                    "codigo_acceso": "55289-124"
                },
                {
                    "id_empleado": "6f02165a-fad5-4455-8a50-d3846e5185cb",
                    "nombre_empleado": "Mélinda",
                    "apellidos_empleado": "Digance",
                    "email_empleado": "tdigance17@wix.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Help Desk Technician",
                    "salario_anual_empleado": 87175,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/inestvoluptatem.png?size=50x50&set=set1",
                    "codigo_acceso": "50844-444"
                },
                {
                    "id_empleado": "b1774127-df1b-4e5d-b3f3-78a43d4fd44b",
                    "nombre_empleado": "Adèle",
                    "apellidos_empleado": "Hulburt",
                    "email_empleado": "bhulburt18@usa.gov",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Accounting",
                    "salario_anual_empleado": 62093,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/etsimiliqueexpedita.png?size=50x50&set=set1",
                    "codigo_acceso": "54868-6286"
                },
                {
                    "id_empleado": "07f69456-35b1-41a7-9d37-0938dd8f0a96",
                    "nombre_empleado": "Océanne",
                    "apellidos_empleado": "Spiaggia",
                    "email_empleado": "cspiaggia19@behance.net",
                    "genero_empleado": "Female",
                    "puesto_empleado": "General Manager",
                    "salario_anual_empleado": 35180,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/ipsanonamet.png?size=50x50&set=set1",
                    "codigo_acceso": "54575-959"
                },
                {
                    "id_empleado": "65924325-59f7-48cd-8c9b-4c85106b275c",
                    "nombre_empleado": "Stéphanie",
                    "apellidos_empleado": "Pearle",
                    "email_empleado": "jpearle1a@friendfeed.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Environmental Tech",
                    "salario_anual_empleado": 29068,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/remestassumenda.png?size=50x50&set=set1",
                    "codigo_acceso": "51079-599"
                },
                {
                    "id_empleado": "226a7399-8b85-4d09-81b8-7f804e66e558",
                    "nombre_empleado": "André",
                    "apellidos_empleado": "Currey",
                    "email_empleado": "rcurrey1b@gizmodo.com",
                    "genero_empleado": "Agender",
                    "puesto_empleado": "Sales Associate",
                    "salario_anual_empleado": 24355,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/omnisnihilsimilique.png?size=50x50&set=set1",
                    "codigo_acceso": "0093-3193"
                },
                {
                    "id_empleado": "2bace1e2-c8f3-41b7-a0fa-a31a0acc8eb5",
                    "nombre_empleado": "Kù",
                    "apellidos_empleado": "Connold",
                    "email_empleado": "aconnold1c@symantec.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Assistant Media Planner",
                    "salario_anual_empleado": 51539,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/placeattotamassumenda.png?size=50x50&set=set1",
                    "codigo_acceso": "36987-3128"
                },
                {
                    "id_empleado": "4f341ec5-a1bc-4ae3-907c-a25a5978091e",
                    "nombre_empleado": "Personnalisée",
                    "apellidos_empleado": "Seals",
                    "email_empleado": "aseals1d@redcross.org",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Help Desk Technician",
                    "salario_anual_empleado": 69193,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/autasperioresducimus.png?size=50x50&set=set1",
                    "codigo_acceso": "13734-136"
                },
                {
                    "id_empleado": "c2ca1ba5-d50b-4f34-bbd5-4f6de9f14d87",
                    "nombre_empleado": "Estève",
                    "apellidos_empleado": "Bittlestone",
                    "email_empleado": "ebittlestone1e@phoca.cz",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Recruiting Manager",
                    "salario_anual_empleado": 52016,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quossitquis.png?size=50x50&set=set1",
                    "codigo_acceso": "0149-0478"
                },
                {
                    "id_empleado": "7ebc1b1c-e282-43b0-ab95-522a12e3d267",
                    "nombre_empleado": "Cinéma",
                    "apellidos_empleado": "Trevallion",
                    "email_empleado": "gtrevallion1f@answers.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Account Representative IV",
                    "salario_anual_empleado": 45804,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/consequunturblanditiisdolor.png?size=50x50&set=set1",
                    "codigo_acceso": "0363-0384"
                },
                {
                    "id_empleado": "dc4e03b0-737c-46d8-9472-a25151c9f7bf",
                    "nombre_empleado": "Uò",
                    "apellidos_empleado": "Pigram",
                    "email_empleado": "cpigram1g@jiathis.com",
                    "genero_empleado": "Bigender",
                    "puesto_empleado": "VP Product Management",
                    "salario_anual_empleado": 34754,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/nullautducimus.png?size=50x50&set=set1",
                    "codigo_acceso": "0093-0926"
                },
                {
                    "id_empleado": "ea860f63-987f-45aa-8223-05b0d96eb4d0",
                    "nombre_empleado": "Chloé",
                    "apellidos_empleado": "Hort",
                    "email_empleado": "lhort1h@pen.io",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Occupational Therapist",
                    "salario_anual_empleado": 32784,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/autlaborumrerum.png?size=50x50&set=set1",
                    "codigo_acceso": "21695-868"
                },
                {
                    "id_empleado": "09b4616c-bdde-4ca0-bc35-a73afe910f8f",
                    "nombre_empleado": "Magdalène",
                    "apellidos_empleado": "Hourigan",
                    "email_empleado": "bhourigan1i@mit.edu",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Executive Secretary",
                    "salario_anual_empleado": 59918,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/temporibusoccaecativoluptatem.png?size=50x50&set=set1",
                    "codigo_acceso": "49288-0408"
                },
                {
                    "id_empleado": "644ad8e0-b635-41cb-9bbb-fe761dd94e36",
                    "nombre_empleado": "Mégane",
                    "apellidos_empleado": "Queyos",
                    "email_empleado": "pqueyos1j@usgs.gov",
                    "genero_empleado": "Female",
                    "puesto_empleado": "VP Accounting",
                    "salario_anual_empleado": 49993,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/delenitiasperioresearum.png?size=50x50&set=set1",
                    "codigo_acceso": "51346-025"
                },
                {
                    "id_empleado": "81c3d8fd-d2da-47a0-be27-bfb3b66c0139",
                    "nombre_empleado": "Marie-hélène",
                    "apellidos_empleado": "Kapelhof",
                    "email_empleado": "dkapelhof1k@comcast.net",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Social Worker",
                    "salario_anual_empleado": 51379,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/ipsameosquibusdam.png?size=50x50&set=set1",
                    "codigo_acceso": "48951-7052"
                },
                {
                    "id_empleado": "fead4690-8a47-43f6-ae86-b2c830d72dad",
                    "nombre_empleado": "Gisèle",
                    "apellidos_empleado": "Tullot",
                    "email_empleado": "ctullot1l@miitbeian.gov.cn",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Graphic Designer",
                    "salario_anual_empleado": 81809,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quosednihil.png?size=50x50&set=set1",
                    "codigo_acceso": "59779-936"
                },
                {
                    "id_empleado": "e447c09d-cd45-47b1-9a97-c5fb7c8ba086",
                    "nombre_empleado": "Séréna",
                    "apellidos_empleado": "Hargate",
                    "email_empleado": "shargate1m@forbes.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Compensation Analyst",
                    "salario_anual_empleado": 72924,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/doloreetcum.png?size=50x50&set=set1",
                    "codigo_acceso": "0555-0956"
                },
                {
                    "id_empleado": "eb433350-96a8-486b-8c9a-f63501e7e2d3",
                    "nombre_empleado": "Françoise",
                    "apellidos_empleado": "Maureen",
                    "email_empleado": "mmaureen1n@nih.gov",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Design Engineer",
                    "salario_anual_empleado": 79977,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/quasisimiliquemollitia.png?size=50x50&set=set1",
                    "codigo_acceso": "49288-0282"
                },
                {
                    "id_empleado": "703c6cbc-979f-4e81-ba7f-aa734e0e5eb4",
                    "nombre_empleado": "Solène",
                    "apellidos_empleado": "Hanhardt",
                    "email_empleado": "bhanhardt1o@opera.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Executive Secretary",
                    "salario_anual_empleado": 45296,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/veroquibusdamqui.png?size=50x50&set=set1",
                    "codigo_acceso": "36987-2879"
                },
                {
                    "id_empleado": "48a6458b-6bca-4103-8236-34ac2d1079fc",
                    "nombre_empleado": "Bérénice",
                    "apellidos_empleado": "Darinton",
                    "email_empleado": "gdarinton1p@histats.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Geological Engineer",
                    "salario_anual_empleado": 50370,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/cumtemporacommodi.png?size=50x50&set=set1",
                    "codigo_acceso": "55154-0525"
                },
                {
                    "id_empleado": "d2db8801-159b-4052-94ea-8f739b5511c0",
                    "nombre_empleado": "Séréna",
                    "apellidos_empleado": "Regina",
                    "email_empleado": "lregina1q@earthlink.net",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Data Coordinator",
                    "salario_anual_empleado": 84745,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/autsuntrerum.png?size=50x50&set=set1",
                    "codigo_acceso": "68479-804"
                },
                {
                    "id_empleado": "605c6451-4638-468a-97e0-5424efb6f154",
                    "nombre_empleado": "Adèle",
                    "apellidos_empleado": "Demann",
                    "email_empleado": "jdemann1r@state.gov",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Occupational Therapist",
                    "salario_anual_empleado": 67565,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/autemiustovel.png?size=50x50&set=set1",
                    "codigo_acceso": "41250-047"
                },
                {
                    "id_empleado": "f2823121-ec01-4e0b-8ccd-c299ff683a19",
                    "nombre_empleado": "Yóu",
                    "apellidos_empleado": "Baszniak",
                    "email_empleado": "abaszniak1s@weebly.com",
                    "genero_empleado": "Genderqueer",
                    "puesto_empleado": "Occupational Therapist",
                    "salario_anual_empleado": 51443,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/voluptatibusnullavoluptatem.png?size=50x50&set=set1",
                    "codigo_acceso": "52125-611"
                },
                {
                    "id_empleado": "763dcb21-80e8-4195-8462-b0a35719b12c",
                    "nombre_empleado": "Marylène",
                    "apellidos_empleado": "Hardeman",
                    "email_empleado": "chardeman1t@unicef.org",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Help Desk Technician",
                    "salario_anual_empleado": 79215,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/minuspossimusmolestias.png?size=50x50&set=set1",
                    "codigo_acceso": "10345-035"
                },
                {
                    "id_empleado": "48f74352-a8a7-4ed3-b391-89f60b3f3dde",
                    "nombre_empleado": "Fèi",
                    "apellidos_empleado": "Aitkin",
                    "email_empleado": "daitkin1u@joomla.org",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Associate Professor",
                    "salario_anual_empleado": 79097,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/deseruntarerum.png?size=50x50&set=set1",
                    "codigo_acceso": "49288-0054"
                },
                {
                    "id_empleado": "1acb7122-6f08-401d-b019-aa6531e521fa",
                    "nombre_empleado": "Pélagie",
                    "apellidos_empleado": "Frayn",
                    "email_empleado": "gfrayn1v@rambler.ru",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Quality Engineer",
                    "salario_anual_empleado": 84300,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/dolorevoluptatumvoluptatem.png?size=50x50&set=set1",
                    "codigo_acceso": "50114-1165"
                },
                {
                    "id_empleado": "c2da19ab-5184-4a0c-9f29-99ab922e4580",
                    "nombre_empleado": "Bérengère",
                    "apellidos_empleado": "Pirrone",
                    "email_empleado": "kpirrone1w@nba.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Analyst Programmer",
                    "salario_anual_empleado": 45628,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/adipisciillumvoluptas.png?size=50x50&set=set1",
                    "codigo_acceso": "50436-3918"
                },
                {
                    "id_empleado": "ca0538cd-34e9-4e54-aa14-3ab70f48e598",
                    "nombre_empleado": "Bérengère",
                    "apellidos_empleado": "O'Cahsedy",
                    "email_empleado": "gocahsedy1x@bigcartel.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Sales Associate",
                    "salario_anual_empleado": 77791,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/idplaceatsunt.png?size=50x50&set=set1",
                    "codigo_acceso": "62670-4764"
                },
                {
                    "id_empleado": "4597119c-8f94-4b0e-8b8e-23a68ff2f37a",
                    "nombre_empleado": "Maëly",
                    "apellidos_empleado": "Hampshaw",
                    "email_empleado": "champshaw1y@bloomberg.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Financial Advisor",
                    "salario_anual_empleado": 57400,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/estperspiciatiscorporis.png?size=50x50&set=set1",
                    "codigo_acceso": "55910-966"
                },
                {
                    "id_empleado": "a364ada8-f2f3-412d-8607-95108f820fa2",
                    "nombre_empleado": "André",
                    "apellidos_empleado": "Keelinge",
                    "email_empleado": "bkeelinge1z@moonfruit.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Sales",
                    "salario_anual_empleado": 43013,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/inciduntsuscipitautem.png?size=50x50&set=set1",
                    "codigo_acceso": "46007-203"
                },
                {
                    "id_empleado": "0ed4e70f-7add-4a7f-b949-dea5b7ea2654",
                    "nombre_empleado": "Zoé",
                    "apellidos_empleado": "Gummoe",
                    "email_empleado": "ogummoe20@163.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Civil Engineer",
                    "salario_anual_empleado": 87981,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/inquasdolores.png?size=50x50&set=set1",
                    "codigo_acceso": "0007-4142"
                },
                {
                    "id_empleado": "a31cf5d6-305c-481d-984e-e6e81059d645",
                    "nombre_empleado": "Eléonore",
                    "apellidos_empleado": "Mantrup",
                    "email_empleado": "fmantrup21@baidu.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Tax Accountant",
                    "salario_anual_empleado": 38986,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/dolorquosapiente.png?size=50x50&set=set1",
                    "codigo_acceso": "0145-0982"
                },
                {
                    "id_empleado": "598a2421-b3b7-4178-a8f6-b7fc8f485939",
                    "nombre_empleado": "Régine",
                    "apellidos_empleado": "Downage",
                    "email_empleado": "rdownage22@xinhuanet.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Speech Pathologist",
                    "salario_anual_empleado": 58751,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/ipsasintquaerat.png?size=50x50&set=set1",
                    "codigo_acceso": "50419-483"
                },
                {
                    "id_empleado": "e367911e-e6d2-480a-9cb8-72a5b8f7d8a7",
                    "nombre_empleado": "Léa",
                    "apellidos_empleado": "Wordesworth",
                    "email_empleado": "lwordesworth23@eventbrite.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Sales Associate",
                    "salario_anual_empleado": 26674,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/quiaquinulla.png?size=50x50&set=set1",
                    "codigo_acceso": "59762-0180"
                },
                {
                    "id_empleado": "177e1c57-8b11-4657-9752-52b188ff1753",
                    "nombre_empleado": "Tú",
                    "apellidos_empleado": "Sultan",
                    "email_empleado": "ssultan24@goo.gl",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Desktop Support Technician",
                    "salario_anual_empleado": 78974,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/inciduntautea.png?size=50x50&set=set1",
                    "codigo_acceso": "68151-0765"
                },
                {
                    "id_empleado": "afebcc87-1dc9-4e4b-99e7-c9d22af165ae",
                    "nombre_empleado": "Joséphine",
                    "apellidos_empleado": "Strewthers",
                    "email_empleado": "estrewthers25@over-blog.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Business Systems Development Analyst",
                    "salario_anual_empleado": 82158,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/laudantiumnesciuntsaepe.png?size=50x50&set=set1",
                    "codigo_acceso": "0941-0424"
                },
                {
                    "id_empleado": "eefe5a91-e965-4864-958f-2839fbd28317",
                    "nombre_empleado": "Zoé",
                    "apellidos_empleado": "Stenners",
                    "email_empleado": "rstenners26@yellowpages.com",
                    "genero_empleado": "Non-binary",
                    "puesto_empleado": "Senior Quality Engineer",
                    "salario_anual_empleado": 76541,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/corruptiipsamea.png?size=50x50&set=set1",
                    "codigo_acceso": "55154-7460"
                },
                {
                    "id_empleado": "adf60946-09d2-4cbc-ac8c-0f5ef8aa2842",
                    "nombre_empleado": "Cléopatre",
                    "apellidos_empleado": "Simkins",
                    "email_empleado": "ssimkins27@home.pl",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Research Assistant II",
                    "salario_anual_empleado": 88900,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/excepturivoluptasexpedita.png?size=50x50&set=set1",
                    "codigo_acceso": "13630-0032"
                },
                {
                    "id_empleado": "5355a606-7f74-4fe7-b336-c9f8ea56630e",
                    "nombre_empleado": "Edmée",
                    "apellidos_empleado": "Stonnell",
                    "email_empleado": "bstonnell28@lycos.com",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Web Designer III",
                    "salario_anual_empleado": 51271,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/illoeostenetur.png?size=50x50&set=set1",
                    "codigo_acceso": "43498-108"
                },
                {
                    "id_empleado": "f29c2585-dacd-482c-8632-e5eab2f15520",
                    "nombre_empleado": "Cinéma",
                    "apellidos_empleado": "Awcoate",
                    "email_empleado": "fawcoate29@sakura.ne.jp",
                    "genero_empleado": "Female",
                    "puesto_empleado": "Geologist II",
                    "salario_anual_empleado": 38817,
                    "seguro_empleado": false,
                    "foto_empleado": "https://robohash.org/consecteturilloquae.png?size=50x50&set=set1",
                    "codigo_acceso": "42254-043"
                },
                {
                    "id_empleado": "46172520-9d8d-4a08-bbb9-4dbbc88c090c",
                    "nombre_empleado": "Réservés",
                    "apellidos_empleado": "Andrusyak",
                    "email_empleado": "aandrusyak2a@xing.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "Sales Associate",
                    "salario_anual_empleado": 37522,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/adabquae.png?size=50x50&set=set1",
                    "codigo_acceso": "60512-6506"
                },
                {
                    "id_empleado": "0326b0cf-3ff4-4cd4-858b-0fff7c85594a",
                    "nombre_empleado": "Dafnée",
                    "apellidos_empleado": "Benedite",
                    "email_empleado": "cbenedite2b@bluehost.com",
                    "genero_empleado": "Non-binary",
                    "puesto_empleado": "Database Administrator II",
                    "salario_anual_empleado": 24106,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/officiaiustocommodi.png?size=50x50&set=set1",
                    "codigo_acceso": "48951-8102"
                },
                {
                    "id_empleado": "15ab69d9-bb94-4654-a4a0-0820232a1407",
                    "nombre_empleado": "Irène",
                    "apellidos_empleado": "Dunniom",
                    "email_empleado": "gdunniom2c@pinterest.com",
                    "genero_empleado": "Male",
                    "puesto_empleado": "VP Marketing",
                    "salario_anual_empleado": 79752,
                    "seguro_empleado": true,
                    "foto_empleado": "https://robohash.org/sitquia.png?size=50x50&set=set1",
                    "codigo_acceso": "53807-158"
                }
            ]
        },
        {
            id_departamento: uuidv4(),
            nombre_departamento: "Marketing",
            jefe_departamento: "Cristina O'donell",
            presupuesto_anual_departamento: 700000,
            empleados_departamento: [
                {
                  "id_empleado": "39765-007",
                  "nombre_empleado": "Mylène",
                  "apellidos_empleado": "Littefair",
                  "email_empleado": "jlittefair0@homestead.com",
                  "genero_empleado": "Polygender",
                  "puesto_empleado": "Associate Professor",
                  "salario_anual_empleado": 33795,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/autculpaaut.png?size=50x50&set=set1",
                  "codigo_acceso": "11822-9860"
                },
                {
                  "id_empleado": "55154-6705",
                  "nombre_empleado": "Noémie",
                  "apellidos_empleado": "Corsan",
                  "email_empleado": "lcorsan1@cdbaby.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Office Assistant III",
                  "salario_anual_empleado": 73253,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/aliquametnesciunt.png?size=50x50&set=set1",
                  "codigo_acceso": "58118-4129"
                },
                {
                  "id_empleado": "48433-307",
                  "nombre_empleado": "Océanne",
                  "apellidos_empleado": "Fortnum",
                  "email_empleado": "afortnum2@github.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Social Worker",
                  "salario_anual_empleado": 70608,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/voluptatumvoluptatesamet.png?size=50x50&set=set1",
                  "codigo_acceso": "55648-554"
                },
                {
                  "id_empleado": "54868-5527",
                  "nombre_empleado": "Cunégonde",
                  "apellidos_empleado": "Takos",
                  "email_empleado": "ctakos3@ameblo.jp",
                  "genero_empleado": "Non-binary",
                  "puesto_empleado": "Programmer II",
                  "salario_anual_empleado": 66901,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/iustomaioresperspiciatis.png?size=50x50&set=set1",
                  "codigo_acceso": "52686-257"
                },
                {
                  "id_empleado": "51367-004",
                  "nombre_empleado": "Östen",
                  "apellidos_empleado": "Coleman",
                  "email_empleado": "mcoleman4@ovh.net",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Nuclear Power Engineer",
                  "salario_anual_empleado": 63963,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/autautofficia.png?size=50x50&set=set1",
                  "codigo_acceso": "36987-2899"
                },
                {
                  "id_empleado": "49873-703",
                  "nombre_empleado": "André",
                  "apellidos_empleado": "Ackrill",
                  "email_empleado": "mackrill5@indiegogo.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Business Systems Development Analyst",
                  "salario_anual_empleado": 75873,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/necessitatibusvoluptasipsum.png?size=50x50&set=set1",
                  "codigo_acceso": "16590-350"
                },
                {
                  "id_empleado": "68788-9116",
                  "nombre_empleado": "Mélina",
                  "apellidos_empleado": "Pauncefoot",
                  "email_empleado": "cpauncefoot6@discuz.net",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Actuary",
                  "salario_anual_empleado": 64566,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/reprehenderitincidunteligendi.png?size=50x50&set=set1",
                  "codigo_acceso": "68788-9686"
                },
                {
                  "id_empleado": "49999-593",
                  "nombre_empleado": "Anaëlle",
                  "apellidos_empleado": "Whylie",
                  "email_empleado": "awhylie7@so-net.ne.jp",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Assistant Media Planner",
                  "salario_anual_empleado": 69921,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/voluptatemreiciendisquae.png?size=50x50&set=set1",
                  "codigo_acceso": "65517-2017"
                },
                {
                  "id_empleado": "0074-3315",
                  "nombre_empleado": "Réjane",
                  "apellidos_empleado": "Simmance",
                  "email_empleado": "lsimmance8@goo.ne.jp",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Director of Sales",
                  "salario_anual_empleado": 73416,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/perspiciatisetquas.png?size=50x50&set=set1",
                  "codigo_acceso": "64578-0089"
                },
                {
                  "id_empleado": "68968-0514",
                  "nombre_empleado": "Mélanie",
                  "apellidos_empleado": "Torrans",
                  "email_empleado": "mtorrans9@dyndns.org",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Food Chemist",
                  "salario_anual_empleado": 86684,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/distinctiovoluptasmaiores.png?size=50x50&set=set1",
                  "codigo_acceso": "0228-3117"
                },
                {
                  "id_empleado": "76237-177",
                  "nombre_empleado": "Pénélope",
                  "apellidos_empleado": "Culp",
                  "email_empleado": "hculpa@nifty.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Dental Hygienist",
                  "salario_anual_empleado": 82041,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/debitiseiusquia.png?size=50x50&set=set1",
                  "codigo_acceso": "36987-1751"
                },
                {
                  "id_empleado": "60574-4113",
                  "nombre_empleado": "Gaëlle",
                  "apellidos_empleado": "Ferris",
                  "email_empleado": "jferrisb@imdb.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Tax Accountant",
                  "salario_anual_empleado": 70934,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/autquoeveniet.png?size=50x50&set=set1",
                  "codigo_acceso": "24724-028"
                }
              ]
        },
        {
            id_departamento: uuidv4(),
            nombre_departamento: "Recursos Humanos",
            jefe_departamento: "Sonia Soria",
            presupuesto_anual_departamento: 220000,
            empleados_departamento: [
                {
                  "id_empleado": "8a3ca0bf-68c7-48db-821e-783e3a76c885",
                  "nombre_empleado": "Séverine",
                  "apellidos_empleado": "Kalaher",
                  "email_empleado": "ckalaher0@home.pl",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Help Desk Operator",
                  "salario_anual_empleado": 52137,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/itaqueomnisvoluptatem.png?size=50x50&set=set1",
                  "codigo_acceso": "66472-041"
                },
                {
                  "id_empleado": "d98477cf-d808-4c32-b570-ad78ffc80968",
                  "nombre_empleado": "Naéva",
                  "apellidos_empleado": "Rolingson",
                  "email_empleado": "crolingson1@eepurl.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Registered Nurse",
                  "salario_anual_empleado": 24777,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/consequunturutmolestiae.png?size=50x50&set=set1",
                  "codigo_acceso": "61924-212"
                },
                {
                  "id_empleado": "00790186-48e4-413d-9bfc-15d5bf188ef4",
                  "nombre_empleado": "Médiamass",
                  "apellidos_empleado": "Denzilow",
                  "email_empleado": "vdenzilow2@shop-pro.jp",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Senior Sales Associate",
                  "salario_anual_empleado": 51558,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/voluptasquiaa.png?size=50x50&set=set1",
                  "codigo_acceso": "55315-559"
                },
                {
                  "id_empleado": "4c18baa8-333e-4ea6-af4b-2f1e0725ff3d",
                  "nombre_empleado": "Irène",
                  "apellidos_empleado": "Castell",
                  "email_empleado": "ccastell3@engadget.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Senior Sales Associate",
                  "salario_anual_empleado": 33637,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/abearumfugit.png?size=50x50&set=set1",
                  "codigo_acceso": "63739-066"
                },
                {
                  "id_empleado": "eb7de17b-6820-4613-97a9-b2f2c4313dfa",
                  "nombre_empleado": "Méthode",
                  "apellidos_empleado": "Whaley",
                  "email_empleado": "bwhaley4@noaa.gov",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Developer III",
                  "salario_anual_empleado": 37415,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/etanimiconsectetur.png?size=50x50&set=set1",
                  "codigo_acceso": "52125-292"
                }
              ]
        },
        {
            id_departamento: uuidv4(),
            nombre_departamento: "Jurídico",
            jefe_departamento: "Sofía Ugena",
            presupuesto_anual_departamento: 450000,
            empleados_departamento: [
                {
                  "id_empleado": "e5173e97-6469-428b-bf9a-7fa7c0836e5a",
                  "nombre_empleado": "Yénora",
                  "apellidos_empleado": "Ortsmann",
                  "email_empleado": "aortsmann0@apache.org",
                  "genero_empleado": "Bigender",
                  "puesto_empleado": "Director of Sales",
                  "salario_anual_empleado": 37217,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/beataenisieum.png?size=50x50&set=set1",
                  "codigo_acceso": "43406-0030"
                },
                {
                  "id_empleado": "982ee92a-e61f-4639-8b51-d57b00bd1c50",
                  "nombre_empleado": "Hélèna",
                  "apellidos_empleado": "Bloxland",
                  "email_empleado": "bbloxland1@devhub.com",
                  "genero_empleado": "Genderqueer",
                  "puesto_empleado": "Quality Engineer",
                  "salario_anual_empleado": 45306,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/sedestsit.png?size=50x50&set=set1",
                  "codigo_acceso": "0615-1593"
                },
                {
                  "id_empleado": "694c0e78-5bff-461d-ac32-711ad10efdfb",
                  "nombre_empleado": "Adélaïde",
                  "apellidos_empleado": "Levington",
                  "email_empleado": "mlevington2@networkadvertising.org",
                  "genero_empleado": "Polygender",
                  "puesto_empleado": "Account Representative IV",
                  "salario_anual_empleado": 68173,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/nostrumeosdeserunt.png?size=50x50&set=set1",
                  "codigo_acceso": "49288-0673"
                },
                {
                  "id_empleado": "9b94d7de-80f6-438f-b2f5-3da8dd3d0e0d",
                  "nombre_empleado": "Thérèsa",
                  "apellidos_empleado": "Fergyson",
                  "email_empleado": "dfergyson3@marketwatch.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Chemical Engineer",
                  "salario_anual_empleado": 62524,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/cupiditateesttenetur.png?size=50x50&set=set1",
                  "codigo_acceso": "11523-7189"
                },
                {
                  "id_empleado": "5cc6cadf-3fc7-4fd9-8c41-ffadca22e1df",
                  "nombre_empleado": "Méng",
                  "apellidos_empleado": "Shulem",
                  "email_empleado": "jshulem4@jimdo.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Community Outreach Specialist",
                  "salario_anual_empleado": 72420,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/maximeautemet.png?size=50x50&set=set1",
                  "codigo_acceso": "42549-511"
                },
                {
                  "id_empleado": "4e81c600-9d61-4a1c-a2d0-2b4a69b5e6e8",
                  "nombre_empleado": "Gösta",
                  "apellidos_empleado": "Raise",
                  "email_empleado": "kraise5@hhs.gov",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Data Coordinator",
                  "salario_anual_empleado": 39935,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/odititaqueautem.png?size=50x50&set=set1",
                  "codigo_acceso": "0031-8693"
                },
                {
                  "id_empleado": "b205b1fa-ae73-4695-a763-45ec1a3887f0",
                  "nombre_empleado": "Maëlyss",
                  "apellidos_empleado": "Paradine",
                  "email_empleado": "dparadine6@slate.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Cost Accountant",
                  "salario_anual_empleado": 73480,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/voluptatesitomnis.png?size=50x50&set=set1",
                  "codigo_acceso": "0603-1587"
                },
                {
                  "id_empleado": "6b4997d5-7232-497e-8c81-c58365dc6f5b",
                  "nombre_empleado": "Annotés",
                  "apellidos_empleado": "Quenby",
                  "email_empleado": "bquenby7@vimeo.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Paralegal",
                  "salario_anual_empleado": 65176,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/consequaturidexpedita.png?size=50x50&set=set1",
                  "codigo_acceso": "65044-2599"
                },
                {
                  "id_empleado": "b567bce6-e4ad-450e-a645-cb8a74e25f54",
                  "nombre_empleado": "Sélène",
                  "apellidos_empleado": "Haig",
                  "email_empleado": "nhaig8@woothemes.com",
                  "genero_empleado": "Non-binary",
                  "puesto_empleado": "Senior Cost Accountant",
                  "salario_anual_empleado": 64058,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/optiodoloresdeserunt.png?size=50x50&set=set1",
                  "codigo_acceso": "68788-9373"
                },
                {
                  "id_empleado": "5637e87c-99a3-49d3-8a9d-836a3a4ce65c",
                  "nombre_empleado": "Göran",
                  "apellidos_empleado": "Collishaw",
                  "email_empleado": "wcollishaw9@sakura.ne.jp",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Developer I",
                  "salario_anual_empleado": 38091,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/vitaequiseius.png?size=50x50&set=set1",
                  "codigo_acceso": "65084-443"
                },
                {
                  "id_empleado": "5ddfa744-8c5e-41f7-ac6d-04c2aa031a4b",
                  "nombre_empleado": "Lài",
                  "apellidos_empleado": "Beeres",
                  "email_empleado": "wbeeresa@indiegogo.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Chief Design Engineer",
                  "salario_anual_empleado": 42191,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/corruptiquosvoluptate.png?size=50x50&set=set1",
                  "codigo_acceso": "0573-2868"
                },
                {
                  "id_empleado": "4a7b2765-4fd4-4729-94a8-f5706e723439",
                  "nombre_empleado": "Gérald",
                  "apellidos_empleado": "Going",
                  "email_empleado": "mgoingb@godaddy.com",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Research Nurse",
                  "salario_anual_empleado": 88337,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/adipiscinumquamvoluptas.png?size=50x50&set=set1",
                  "codigo_acceso": "0085-1304"
                },
                {
                  "id_empleado": "f6561d62-515d-42d1-84d6-ca6d5a214d71",
                  "nombre_empleado": "Hélène",
                  "apellidos_empleado": "Waine",
                  "email_empleado": "awainec@wiley.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Staff Scientist",
                  "salario_anual_empleado": 63407,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/omnisquaeratid.png?size=50x50&set=set1",
                  "codigo_acceso": "76439-345"
                },
                {
                  "id_empleado": "79cdf48d-2fe7-49fa-b301-3fd2ff68a158",
                  "nombre_empleado": "Fèi",
                  "apellidos_empleado": "Klauer",
                  "email_empleado": "aklauerd@smh.com.au",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Clinical Specialist",
                  "salario_anual_empleado": 89782,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/assumendavoluptatemvoluptatem.png?size=50x50&set=set1",
                  "codigo_acceso": "0268-1412"
                },
                {
                  "id_empleado": "a72b6cc6-41ca-479b-90cc-cdaba6500b74",
                  "nombre_empleado": "Michèle",
                  "apellidos_empleado": "Kellett",
                  "email_empleado": "lkellette@mozilla.org",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Administrative Officer",
                  "salario_anual_empleado": 72228,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/sitsintet.png?size=50x50&set=set1",
                  "codigo_acceso": "0065-0345"
                },
                {
                  "id_empleado": "559e2048-3222-443d-842a-8374b29c079b",
                  "nombre_empleado": "Torbjörn",
                  "apellidos_empleado": "Inker",
                  "email_empleado": "pinkerf@123-reg.co.uk",
                  "genero_empleado": "Female",
                  "puesto_empleado": "Marketing Assistant",
                  "salario_anual_empleado": 43839,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/inventorelaborumvoluptatem.png?size=50x50&set=set1",
                  "codigo_acceso": "0904-5577"
                },
                {
                  "id_empleado": "8a8ecddd-4ee4-4951-a367-5d6f9ba7d06a",
                  "nombre_empleado": "Åke",
                  "apellidos_empleado": "Trevenu",
                  "email_empleado": "atrevenug@timesonline.co.uk",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Pharmacist",
                  "salario_anual_empleado": 75675,
                  "seguro_empleado": false,
                  "foto_empleado": "https://robohash.org/eiusquiillum.png?size=50x50&set=set1",
                  "codigo_acceso": "59779-615"
                },
                {
                  "id_empleado": "8aac1358-59be-495d-8a58-98af59edfc61",
                  "nombre_empleado": "Solène",
                  "apellidos_empleado": "Blogg",
                  "email_empleado": "obloggh@ft.com",
                  "genero_empleado": "Male",
                  "puesto_empleado": "Tax Accountant",
                  "salario_anual_empleado": 45404,
                  "seguro_empleado": true,
                  "foto_empleado": "https://robohash.org/voluptasnecessitatibusdolorem.png?size=50x50&set=set1",
                  "codigo_acceso": "68462-160"
                }
              ]
        }
    ],
    
}

export default data;